### PR TITLE
Updating make config to build a dynamic module

### PR DESCRIPTION
**Pull request by anitakrueger**
This updated config will make the module build a .so file. I am still in the middle of testing though, because I don't know if my config is wrong or if the module isn't working, because I am currently only getting `400` errors when trying to use CONNECT.

### CODE REVIEW

**Comment by chobits** [comment]
Let me check, for first glance, I think this pull request is right.

>  because I am currently only getting 400 errors when trying to use CONNECT.

Maybe you load this .so file on nginx without proxy_connect patch?

Because it depends patched nginx core to run this module, the module .so cannot work on unpatched nginx binary.

**Comment by chobits** [comment]
There are test cases in `<source>/t`, it can work only for static building module.

```
$ hg clone http://hg.nginx.org/nginx-tests/

$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/Users/xiaochen/work/github/nginx-1.14.2/objs/nginx prove -v -I /path/to/nginx-tests/lib /path/to/ngx_http_proxy_connect_module/t/
```

**Comment by chobits** [comment]
Have checked your config diff on nginx-1.14 with static built proxy_connect module.
The compilation and test cases have passed.

# Test Case:
* Tested-by: Xiaochen Wang
* Date: Wed Jun 19 12:14:37 CST 2019
* pwd: /Users/xiaochen/work/github/nginx-1.14.2
* cases: `../ngx_http_proxy_connect_module/t`

* case result:

```

$ git diff
diff --git a/config b/config
index f97e455..a840909 100644
--- a/config
+++ b/config
@@ -1,5 +1,12 @@
 ngx_addon_name=ngx_http_proxy_connect_module
-HTTP_MODULES="$HTTP_MODULES ngx_http_proxy_connect_module"
-NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_proxy_connect_module.c"

+if test -n "$ngx_module_link"; then
+    ngx_module_type=HTTP
+    ngx_module_name=ngx_http_proxy_connect_module
+    ngx_module_srcs="$ngx_addon_dir/ngx_http_proxy_connect_module.c"
+    . auto/module
+else
+    HTTP_MODULES="$HTTP_MODULES ngx_http_proxy_connect_module"
+    NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_proxy_connect_module.c"
+fi
 have=NGX_HTTP_PROXY_CONNECT . auto/have


$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/Users/xiaochen/work/github/nginx-1.14.2/objs/nginx prove -I /Users/xiaochen/work/github/nginx-1.14.2/../nginx-tests/lib ../ngx_http_proxy_connect_module/t
../ngx_http_proxy_connect_module/t/http_proxy_connect.t .......... All 17 subtests passed
../ngx_http_proxy_connect_module/t/http_proxy_connect_timeout.t .. All 4 subtests passed

**Comment by chobits** [comment]
Have checked dynamic built module, my test step as following:

```

output :: (master*) $ cat ../genmake.sh
./configure --prefix=$(pwd)/output   --with-http_ssl_module  --add-dynamic-module=../ngx_http_proxy_connect_module/ \
    --with-cc-opt="-I/usr/local/opt/openssl/include -O0 -g" \
    --with-ld-opt="-L/usr/local/opt/openssl/lib" \
    --with-debug
output :: (master*) $ cat conf/nginx.conf

worker_processes  1;
error_log  logs/error.log;
pid        logs/nginx.pid;

load_module modules/ngx_http_proxy_connect_module.so;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen                         3128;

        # dns resolver used by forward proxying
        resolver                       8.8.8.8;

        # forward proxy for CONNECT request
        proxy_connect;
        proxy_connect_allow            443 563;
        proxy_connect_connect_timeout  10s;
        proxy_connect_read_timeout     10s;
        proxy_connect_send_timeout     10s;

        # forward proxy for non-CONNECT request
        location / {
            proxy_pass http://$host;
            proxy_set_header Host $host;
        }
    }
}
output :: (master*) $ curl https://github.com -x localhost:3128 -sv -o /dev/null
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 3128 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to github.com:443
> CONNECT github.com:443 HTTP/1.1
> Host: github.com:443
> User-Agent: curl/7.62.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection Established
< Proxy-agent: nginx
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* CONNECT phase completed!
* CONNECT phase completed!
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: github.com
* Server certificate: DigiCert SHA2 Extended Validation Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET / HTTP/1.1
> Host: github.com
> User-Agent: curl/7.62.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Wed, 19 Jun 2019 06:48:41 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Server: GitHub.com
< Status: 200 OK
< Vary: X-PJAX
< ETag: W/"2063a21066aa100512e48d1a37eb98c1"
< Cache-Control: max-age=0, private, must-revalidate
< Set-Cookie: has_recent_activity=1; path=/; expires=Wed, 19 Jun 2019 07:48:41 -0000
< Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sun, 19 Jun 2039 06:48:41 -0000; secure; HttpOnly
< Set-Cookie: _gh_sess=Um1QNWJ6SW5xWFNOUGdzYWZibDcrVmtOV1lTVUNXeWpGY0I1QlBOQ1hqRlFRU3A0TmpyOU1PdXdra0tyNUlOeTFYRUVuQnJaWW9jUHpxQlNXeVJvRFgvSUk0VkNqU3FKTEk3dU1FalZKSGpXOEhyUDlHRWFFNVNjeElIdnlQSXpwODhRblg3SkJlWHpCR2lPR3BXWktkTGNUcGwydDQ2NHF1cGJFSlJtSkU4ZDYwL0RzSzJ2QWtTVVRjRnFmcW9FbTRBQ2FMcDNqZzU0V2JyVWdEUlJZdz09LS1kSlF6ZnY1ZEF2ZVd1elozdEhleXpRPT0%3D--af29b1e217ba9101d810b4a5926e9b9821ffc64d; path=/; secure; HttpOnly
< X-Request-Id: 84b96182-95d2-438f-8d2f-d0a0163577f8
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
< Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com customer-stories-feed.github.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com
< Vary: Accept-Encoding
< X-GitHub-Request-Id: 1F63:7503:3E7215:5E4F3D:5D09DAC8
<
{ [1370 bytes data]
* Connection #0 to host localhost left intact
```

**Comment by chobits** [comment]
I have updated README.md for loading dynamic module.

* See PR https://github.com/chobits/ngx_http_proxy_connect_module/pull/111.
* See README.md: https://github.com/chobits/ngx_http_proxy_connect_module#build-as-a-dynamic-module

**Comment by anitakrueger** [comment]
> Let me check, for first glance, I think this pull request is right.
> 
> > because I am currently only getting 400 errors when trying to use CONNECT.
> 
> Maybe you load this .so file on nginx without proxy_connect patch?
> 
> Because it depends patched nginx core to run this module, the module .so cannot work on unpatched nginx binary.

@chobits That must be my issue then. I was using the stock nginx package together with the dynamically built module. But obviously the stock nginx package doesn't have the patch.
We do this as a standard practice for loading modules, so that we know we always use the standard nginx, not a self-compiled one.
So looks like I'll have to patch, compile and package nginx then.

**Comment by anitakrueger** [comment]
Thank you for your quick response on this! Appreciate it!

**Pull request merged**
