### PR TITLE
added new variable $connect_addr

### PR DESCRIPTION
**Pull request by chobits**
* added new variable $connect_addr: IP address and port of the remote host, e.g. "192.168.1.1:12345"
* added test case for $connect_host/$connect_port/$connect_addr
* added documentation of these variables

### CODE REVIEW

**Comment by chobits** [comment]
```
$ MOD_DYCONF_PATH=/Users/tomoyo/work/github/ngx_http_proxy_connect_module TEST_NGINX_BINARY=/Users/tomoyo/work/github/nginx/objs/nginx prove -v -I /Users/tomoyo/work/github/nginx-tests/lib t/http_proxy_connect.t
t/http_proxy_connect.t ..
1..11
ok 1 - 200 Connection Established
ok 2 - 200 Connection Established server name
ok 3 - 200 Connection Established server name
ok 4 - 200 Connection Established server name
ok 5 - 200 Connection Established not allowed port
ok 6 - Get method: proxy_pass
ok 7 - Get method: return 200
ok 8 - $connect_host, $connect_port, $connect_addr
ok 9 - empty variable $connect_addr
ok 10 - no alerts
ok 11 - no sanitizer errors
ok
All tests successful.
Files=1, Tests=11,  2 wallclock secs ( 0.03 usr  0.01 sys +  0.08 cusr  0.03 csys =  0.15 CPU)
Result: PASS
```

**Comment by chobits** [comment]
preview documentation:

Variables
=========

$connect_host
-------------

host name from CONNECT request line

$connect_port
-------------

port from CONNECT request line

$connect_addr
-------------

IP address and port of the remote host, e.g. "192.168.1.5:12345"
IP address is resolved from host name of CONNECT request line

**Comment by aholic** [comment]
ack

**Comment by chobits** [comment]
Not move `$connect_host` and `$connect_port` from patch into this module source, because these variables use feilds of ngx_http_request_t.

**Pull request merged**
